env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = NIXOS_OZONE_WL,1
env = QT_QPA_PLATFORMTHEME,kde
env = QT_SCALE_FACTOR,1
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24


monitor=DP-1,1920x1080@144,0x0,1
monitor=DP-3,1920x1080@60,1920x0,1
monitor=HDMI-A-1,1920x1080@60,1920x1080,1

workspace = 1, monitor:DP-1, persistent:true
workspace = 2, monitor:DP-1, persistent:true
workspace = 3, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-1, persistent:true
workspace = 5, monitor:DP-1, persistent:true
workspace = 6, monitor:DP-3, persistent:true
workspace = 7, monitor:DP-3, persistent:true
workspace = 8, monitor:DP-3, persistent:true
workspace = 9, monitor:DP-3, persistent:true
workspace = 10, monitor:DP-3, persistent:true

cursor {
    no_hardware_cursors = true
}

input {
    kb_layout = de
    kb_variant =
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

general {
    gaps_in = 5
    gaps_out = 5 5 5 5
    border_size = 2
    col.active_border = rgba(2d6a4fff) rgba(40916cff) 45deg
    col.inactive_border = rgba(1b2d24ff)
    layout = dwindle
}

decoration {
    rounding = 14
    blur {
        enabled = true
        size = 10
        passes = 3
        vibrancy = 0.3
        new_optimizations = true
        xray = false
    }
    shadow {
        enabled = true
        range = 30
        render_power = 4
        color = rgba(00000044)
    }
    active_opacity = 1.0
    inactive_opacity = 0.85
}

animations {
    enabled = true
    bezier = smooth,0.05,0.9,0.1,1.05
    animation = windows,1,5,smooth,slide
    animation = fade,1,4,default
    animation = workspaces,1,4,smooth,slide
}

dwindle {
    pseudotile = true
    preserve_split = true
}

$mod = SUPER

bind = $mod,Q,exec,kitty
bind = $mod,C,killactive
bind = $mod,F,fullscreen
bind = $mod,V,togglefloating
bind = $mod,R,exec,rofi -show drun
bind = $mod,1,workspace,1
bind = $mod,2,workspace,2
bind = $mod,3,workspace,3
bind = $mod,4,workspace,4
bind = $mod,5,workspace,5
bind = $mod,6,workspace,6
bind = $mod,7,workspace,7
bind = $mod,8,workspace,8
bind = $mod,9,workspace,9
bind = $mod,0,workspace,10
bind = $mod SHIFT,1,movetoworkspace,1
bind = $mod SHIFT,2,movetoworkspace,2
bind = $mod SHIFT,3,movetoworkspace,3
bind = $mod SHIFT,4,movetoworkspace,4
bind = $mod SHIFT,5,movetoworkspace,5
bind = $mod SHIFT,6,movetoworkspace,6
bind = $mod SHIFT,7,movetoworkspace,7
bind = $mod SHIFT,8,movetoworkspace,8
bind = $mod SHIFT,9,movetoworkspace,9
bind = $mod SHIFT,0,movetoworkspace,10
bindm = $mod,mouse:272,movewindow
bindm = $mod,mouse:273,resizewindow
bind = SUPER,S,exec,grim -g "$(slurp)"~/pictures/screenshot.png
bind = $mod,N,exec,nix-manager
bind = $mod SHIFT,N,exec,swaync-client -t
bind = $mod,P,exec,~/.local/bin/media-toggle

submap = mediapicker
bind = ,escape,exec,eww close media-picker; hyprctl dispatch submap reset
submap = reset
bind = SUPER, T, exec, ~/.config/skwd-wall/scripts/toggle-ui.sh

exec-once = systemctl --user start graphical-session.target
exec-once = systemctl --user start ambient-daemon
exec-once = waybar &
exec-once = swww-daemon
exec-once = skwd-daemon
exec-once = nwg-dock-hyprland -d -i 52 -mb 8 -ml 6 -mr 6
exec-once = swaync
exec-once = hypridle
exec-once = openrgb --server
exec-once = awww-daemon
exec-once = sleep 2 && eww open sysmon

windowrule {
    name = nautilus-opacity
    match:class = ^(org.gnome.Nautilus)$
    opacity = 0.88 0.82
}

blurls = hotspot

